# Döntési fa std


## Adatok betöltése

In [15]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_bc050f45180b4c1bb8886542b85a43fe = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='6akYbYHItNWmuiZPpgS8f0DnZNTVPSN3hYgF_EVLfHhd',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

body = client_bc050f45180b4c1bb8886542b85a43fe.get_object(Bucket='szakdolgozat-donotdelete-pr-nxru0g4tgksnkv',Key='Standard_train.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

train_input = pd.read_csv(body, sep=';',decimal=',')
train_input.head(10)


DPD90_12m  customer_type  product_type_zart  product_type_nyilt     onero  \
0          0              1                  1                   0  0.982666   
1          0              1                  1                   0 -0.474430   
2          0              1                  1                   0 -0.474430   
3          0              1                  1                   0  1.104222   
4          0              1                  1                   0 -0.271573   
5          0              1                  1                   0 -0.474430   
6          0              0                  1                   0  3.487986   
7          0              1                  1                   0  0.115986   
8          0              1                  1                   0 -1.263756   
9          0              1                  1                   0 -0.474430   

   age_of_asset (honap)  sales_channel_dealer  sales_channel_hitelpont  \
0             -0.540714                     1                        0   
1              2.285552                     0                        0   
2              1.225702                     1                        0   
3             -0.540714                     1                        0   
4             -0.540714                     1                        0   
5              0.872419                     0                        0   
6             -0.540714                     1                        0   
7             -0.540714                     1                        0   
8             -0.219548                     1                        0   
9              1.161469                     1                        0   

   sales_channel_hiteliroda  Nace_low  Nace_medium  Nace_high  
0                         0         1            0          0  
1                         1         0            0          1  
2                         0         0            1          0  
3                         0         0            1          0  
4                         0         0            1          0  
5                         1         1            0          0  
6                         0         1            0          0  
7                         0         1            0          0  
8                         0         0            1          0  
9                         0         1            0          0

In [16]:

body = client_bc050f45180b4c1bb8886542b85a43fe.get_object(Bucket='szakdolgozat-donotdelete-pr-nxru0g4tgksnkv',Key='Standard_test.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

test_input = pd.read_csv(body, sep=';',decimal=',')
test_input.head()


DPD90_12m  customer_type  product_type_zart  product_type_nyilt     onero  \
0          0              1                  1                   0  0.314896   
1          0              1                  1                   0 -0.474430   
2          0              1                  1                   0  1.618863   
3          0              1                  1                   0  1.104222   
4          0              1                  1                   0 -0.474430   

   age_of_asset (honap)  sales_channel_dealer  sales_channel_hitelpont  \
0             -0.540714                     1                        0   
1              2.670952                     0                        0   
2             -0.540714                     1                        0   
3             -0.540714                     1                        0   
4             -0.540714                     1                        0   

   sales_channel_hiteliroda  Nace_low  Nace_medium  Nace_high  
0                         0         1            0          0  
1                         1         1            0          0  
2                         0         1            0          0  
3                         0         1            0          0  
4                         0         0            0          1

In [17]:
train_input.shape

(7339, 12)

In [18]:
test_input.shape

(3083, 12)

## Adatok előkészítése

In [19]:
import numpy as np

In [20]:
X_train = np.asarray(train_input[['product_type_zart', 'product_type_nyilt', 'sales_channel_dealer', 'onero', 'age_of_asset (honap)', 'Nace_low', 'Nace_medium', 'Nace_high']])
X_train[0:1]

array([[ 1.        ,  0.        ,  1.        ,  0.98266592, -0.54071439,
         1.        ,  0.        ,  0.        ]])

In [21]:
X_test = np.asarray(test_input[['product_type_zart', 'product_type_nyilt', 'sales_channel_dealer', 'onero', 'age_of_asset (honap)', 'Nace_low', 'Nace_medium', 'Nace_high']])
X_test[0:1]

array([[ 1.        ,  0.        ,  1.        ,  0.31489619, -0.54071439,
         1.        ,  0.        ,  0.        ]])

In [22]:
y_train = np.asarray(train_input['DPD90_12m'])
y_train [0:5]

array([0, 0, 0, 0, 0])

In [23]:
y_test = np.asarray(test_input['DPD90_12m'])
y_test [0:5]

array([0, 0, 0, 0, 0])

## Modellezés

In [130]:
from sklearn.tree import DecisionTreeClassifier
LR = DecisionTreeClassifier(criterion="entropy", max_depth = 7, min_samples_split=0.2).fit(X_train,y_train)
LR

DecisionTreeClassifier(criterion='entropy', max_depth=7, min_samples_split=0.2)

In [131]:
yhat_test = LR.predict_proba(X_test)
yhat_test

array([[0.9969419 , 0.0030581 ],
       [0.91777188, 0.08222812],
       [1.        , 0.        ],
       ...,
       [0.91777188, 0.08222812],
       [0.91777188, 0.08222812],
       [0.9969419 , 0.0030581 ]])

In [132]:
yhat_train = LR.predict_proba(X_train)
yhat_train

array([[1.        , 0.        ],
       [0.91777188, 0.08222812],
       [0.95087719, 0.04912281],
       ...,
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.95823096, 0.04176904]])

In [133]:
tech, y_predicted_train = zip(*yhat_train)
y_predicted_train[0:5]

(0.0,
 0.08222811671087533,
 0.04912280701754386,
 0.01016260162601626,
 0.021086780210867802)

In [134]:
tech, y_predicted_test = zip(*yhat_test)
y_predicted_test[0:5]

(0.0030581039755351682, 0.08222811671087533, 0.0, 0.0, 0.04176904176904177)

## Modell ereje

In [135]:
from sklearn.metrics import roc_auc_score
roc=roc_auc_score(y_train, y_predicted_train)
gini=2*roc-1
gini

0.5289065772936739

In [136]:
from sklearn.metrics import roc_auc_score
roc=roc_auc_score(y_test, y_predicted_test)
gini=2*roc-1
gini

0.49327751423559807