# GBM std


## Adatok betöltése

In [1]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_bc050f45180b4c1bb8886542b85a43fe = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='6akYbYHItNWmuiZPpgS8f0DnZNTVPSN3hYgF_EVLfHhd',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

body = client_bc050f45180b4c1bb8886542b85a43fe.get_object(Bucket='szakdolgozat-donotdelete-pr-nxru0g4tgksnkv',Key='Standard_train.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

train_input = pd.read_csv(body, sep=';',decimal=',')
train_input.head(10)


DPD90_12m  customer_type  product_type_zart  product_type_nyilt     onero  \
0          0              1                  1                   0  0.982666   
1          0              1                  1                   0 -0.474430   
2          0              1                  1                   0 -0.474430   
3          0              1                  1                   0  1.104222   
4          0              1                  1                   0 -0.271573   
5          0              1                  1                   0 -0.474430   
6          0              0                  1                   0  3.487986   
7          0              1                  1                   0  0.115986   
8          0              1                  1                   0 -1.263756   
9          0              1                  1                   0 -0.474430   

   age_of_asset (honap)  sales_channel_dealer  sales_channel_hitelpont  \
0             -0.540714                     1                        0   
1              2.285552                     0                        0   
2              1.225702                     1                        0   
3             -0.540714                     1                        0   
4             -0.540714                     1                        0   
5              0.872419                     0                        0   
6             -0.540714                     1                        0   
7             -0.540714                     1                        0   
8             -0.219548                     1                        0   
9              1.161469                     1                        0   

   sales_channel_hiteliroda  Nace_low  Nace_medium  Nace_high  
0                         0         1            0          0  
1                         1         0            0          1  
2                         0         0            1          0  
3                         0         0            1          0  
4                         0         0            1          0  
5                         1         1            0          0  
6                         0         1            0          0  
7                         0         1            0          0  
8                         0         0            1          0  
9                         0         1            0          0

In [2]:

body = client_bc050f45180b4c1bb8886542b85a43fe.get_object(Bucket='szakdolgozat-donotdelete-pr-nxru0g4tgksnkv',Key='Standard_test.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

test_input = pd.read_csv(body, sep=';',decimal=',')
test_input.head()


DPD90_12m  customer_type  product_type_zart  product_type_nyilt     onero  \
0          0              1                  1                   0  0.314896   
1          0              1                  1                   0 -0.474430   
2          0              1                  1                   0  1.618863   
3          0              1                  1                   0  1.104222   
4          0              1                  1                   0 -0.474430   

   age_of_asset (honap)  sales_channel_dealer  sales_channel_hitelpont  \
0             -0.540714                     1                        0   
1              2.670952                     0                        0   
2             -0.540714                     1                        0   
3             -0.540714                     1                        0   
4             -0.540714                     1                        0   

   sales_channel_hiteliroda  Nace_low  Nace_medium  Nace_high  
0                         0         1            0          0  
1                         1         1            0          0  
2                         0         1            0          0  
3                         0         1            0          0  
4                         0         0            0          1

In [3]:
train_input.shape

(7339, 12)

In [4]:
test_input.shape

(3083, 12)

## Adatok előkészítése

In [5]:
import numpy as np

In [6]:
X_train = np.asarray(train_input[['customer_type', 'product_type_zart', 'product_type_nyilt', 'sales_channel_dealer', 'sales_channel_hiteliroda', 'sales_channel_hitelpont', 'onero', 'age_of_asset (honap)', 'Nace_low', 'Nace_medium', 'Nace_high']])
X_train[0:1]

array([[ 1.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.98266592, -0.54071439,  1.        ,  0.        ,
         0.        ]])

In [7]:
X_test = np.asarray(test_input[['customer_type', 'product_type_zart', 'product_type_nyilt', 'sales_channel_dealer', 'sales_channel_hiteliroda', 'sales_channel_hitelpont', 'onero', 'age_of_asset (honap)', 'Nace_low', 'Nace_medium', 'Nace_high']])
X_test[0:1]

array([[ 1.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.31489619, -0.54071439,  1.        ,  0.        ,
         0.        ]])

In [8]:
y_train = np.asarray(train_input['DPD90_12m'])
y_train [0:5]

array([0, 0, 0, 0, 0])

In [9]:
y_test = np.asarray(test_input['DPD90_12m'])
y_test [0:5]

array([0, 0, 0, 0, 0])

## Modellezés

In [115]:
from sklearn.ensemble import GradientBoostingClassifier
LR = GradientBoostingClassifier(max_depth = 1, min_samples_split=0.05, n_estimators=100, learning_rate=0.115).fit(X_train,y_train)
LR

GradientBoostingClassifier(learning_rate=0.115, max_depth=1,
                           min_samples_split=0.05)

In [116]:
yhat_test = LR.predict_proba(X_test)
yhat_test

array([[0.99019635, 0.00980365],
       [0.91877855, 0.08122145],
       [0.99358926, 0.00641074],
       ...,
       [0.95196351, 0.04803649],
       [0.83757281, 0.16242719],
       [0.98948808, 0.01051192]])

In [117]:
yhat_train = LR.predict_proba(X_train)
yhat_train

array([[0.99019635, 0.00980365],
       [0.7809675 , 0.2190325 ],
       [0.96477117, 0.03522883],
       ...,
       [0.99055588, 0.00944412],
       [0.99252558, 0.00747442],
       [0.94037502, 0.05962498]])

In [118]:
tech, y_predicted_train = zip(*yhat_train)
y_predicted_train[0:5]

(0.009803646301388505,
 0.21903250195475044,
 0.03522882685591141,
 0.013572600745144499,
 0.017768168977244248)

In [119]:
tech, y_predicted_test = zip(*yhat_test)
y_predicted_test[0:5]

(0.009803646301388505,
 0.08122145404443534,
 0.006410741371224958,
 0.007474416542871066,
 0.03381664336936604)

## Modell ereje

In [120]:
from sklearn.metrics import roc_auc_score
roc=roc_auc_score(y_train, y_predicted_train)
gini=2*roc-1
gini

0.5428695383389113

In [121]:
from sklearn.metrics import roc_auc_score
roc=roc_auc_score(y_test, y_predicted_test)
gini=2*roc-1
gini

0.5373149804287527