# Neural Network std


## Adatok betöltése

In [1]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_bc050f45180b4c1bb8886542b85a43fe = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='6akYbYHItNWmuiZPpgS8f0DnZNTVPSN3hYgF_EVLfHhd',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

body = client_bc050f45180b4c1bb8886542b85a43fe.get_object(Bucket='szakdolgozat-donotdelete-pr-nxru0g4tgksnkv',Key='Standard_train.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

train_input = pd.read_csv(body, sep=';',decimal=',')
train_input.head(10)


DPD90_12m  customer_type  product_type_zart  product_type_nyilt     onero  \
0          0              1                  1                   0  0.982666   
1          0              1                  1                   0 -0.474430   
2          0              1                  1                   0 -0.474430   
3          0              1                  1                   0  1.104222   
4          0              1                  1                   0 -0.271573   
5          0              1                  1                   0 -0.474430   
6          0              0                  1                   0  3.487986   
7          0              1                  1                   0  0.115986   
8          0              1                  1                   0 -1.263756   
9          0              1                  1                   0 -0.474430   

   age_of_asset (honap)  sales_channel_dealer  sales_channel_hitelpont  \
0             -0.540714                     1                        0   
1              2.285552                     0                        0   
2              1.225702                     1                        0   
3             -0.540714                     1                        0   
4             -0.540714                     1                        0   
5              0.872419                     0                        0   
6             -0.540714                     1                        0   
7             -0.540714                     1                        0   
8             -0.219548                     1                        0   
9              1.161469                     1                        0   

   sales_channel_hiteliroda  Nace_low  Nace_medium  Nace_high  
0                         0         1            0          0  
1                         1         0            0          1  
2                         0         0            1          0  
3                         0         0            1          0  
4                         0         0            1          0  
5                         1         1            0          0  
6                         0         1            0          0  
7                         0         1            0          0  
8                         0         0            1          0  
9                         0         1            0          0

In [2]:

body = client_bc050f45180b4c1bb8886542b85a43fe.get_object(Bucket='szakdolgozat-donotdelete-pr-nxru0g4tgksnkv',Key='Standard_test.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

test_input = pd.read_csv(body, sep=';',decimal=',')
test_input.head()


DPD90_12m  customer_type  product_type_zart  product_type_nyilt     onero  \
0          0              1                  1                   0  0.314896   
1          0              1                  1                   0 -0.474430   
2          0              1                  1                   0  1.618863   
3          0              1                  1                   0  1.104222   
4          0              1                  1                   0 -0.474430   

   age_of_asset (honap)  sales_channel_dealer  sales_channel_hitelpont  \
0             -0.540714                     1                        0   
1              2.670952                     0                        0   
2             -0.540714                     1                        0   
3             -0.540714                     1                        0   
4             -0.540714                     1                        0   

   sales_channel_hiteliroda  Nace_low  Nace_medium  Nace_high  
0                         0         1            0          0  
1                         1         1            0          0  
2                         0         1            0          0  
3                         0         1            0          0  
4                         0         0            0          1

In [3]:
train_input.shape

(7339, 12)

In [4]:
test_input.shape

(3083, 12)

## Adatok előkészítése

In [5]:
import numpy as np

In [6]:
X_train = np.asarray(train_input[['customer_type','product_type_zart', 'sales_channel_dealer', 'onero', 'age_of_asset (honap)', 'Nace_low', 'Nace_medium', 'Nace_high']])
X_train[0:1]

array([[ 1.        ,  1.        ,  1.        ,  0.98266592, -0.54071439,
         1.        ,  0.        ,  0.        ]])

In [7]:
X_test = np.asarray(test_input[['customer_type','product_type_zart', 'sales_channel_dealer', 'onero', 'age_of_asset (honap)', 'Nace_low', 'Nace_medium', 'Nace_high']])
X_test[0:1]

array([[ 1.        ,  1.        ,  1.        ,  0.31489619, -0.54071439,
         1.        ,  0.        ,  0.        ]])

In [8]:
y_train = np.asarray(train_input['DPD90_12m'])
y_train [0:5]

array([0, 0, 0, 0, 0])

In [9]:
y_test = np.asarray(test_input['DPD90_12m'])
y_test [0:5]

array([0, 0, 0, 0, 0])

## Modellezés

In [31]:
import tensorflow as tf
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1, activation='sigmoid')
    
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=20)

Train on 7339 samples
Epoch 1/20
7339/7339 [==============================] - 156s 21ms/sample - loss: 0.2184 - accuracy: 0.9563
Epoch 2/20
7339/7339 [==============================] - 151s 21ms/sample - loss: 0.1334 - accuracy: 0.9756
Epoch 3/20
7339/7339 [==============================] - 155s 21ms/sample - loss: 0.1310 - accuracy: 0.9755
Epoch 4/20
7339/7339 [==============================] - 154s 21ms/sample - loss: 0.1231 - accuracy: 0.9757
Epoch 5/20
7339/7339 [==============================] - 156s 21ms/sample - loss: 0.1251 - accuracy: 0.9757
Epoch 6/20
7339/7339 [==============================] - 156s 21ms/sample - loss: 0.1218 - accuracy: 0.9757
Epoch 7/20
7339/7339 [==============================] - 167s 23ms/sample - loss: 0.1218 - accuracy: 0.9757
Epoch 8/20
7339/7339 [==============================] - 171s 23ms/sample - loss: 0.1174 - accuracy: 0.9757
Epoch 9/20
7339/7339 [==============================] - 170s 23ms/sample - loss: 0.1166 - accuracy: 0.9757
Epoch 10/20
733

In [32]:
yhat_test = model.predict(X_test)
yhat_test

array([[0.00678406],
       [0.09723433],
       [0.00228346],
       ...,
       [0.0262382 ],
       [0.10436216],
       [0.00469543]], dtype=float32)

In [33]:
yhat_train = model.predict(X_train)
yhat_train

array([[0.00388666],
       [0.11544807],
       [0.06659751],
       ...,
       [0.00138314],
       [0.00217204],
       [0.09748129]], dtype=float32)

## Modell ereje

In [34]:
from sklearn.metrics import roc_auc_score
roc=roc_auc_score(y_train, yhat_train)
gini=2*roc-1
gini

0.5504158762585729

In [35]:
from sklearn.metrics import roc_auc_score
roc=roc_auc_score(y_test, yhat_test)
gini=2*roc-1
gini

0.5157650067829709