# Neural Network woe


## Adatok betöltése

In [1]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_bc050f45180b4c1bb8886542b85a43fe = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='6akYbYHItNWmuiZPpgS8f0DnZNTVPSN3hYgF_EVLfHhd',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

body = client_bc050f45180b4c1bb8886542b85a43fe.get_object(Bucket='szakdolgozat-donotdelete-pr-nxru0g4tgksnkv',Key='WOE_train.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

train_input = pd.read_csv(body, sep=';',decimal=',')
train_input.head(10)


DPD90_12m  customer_type  product_type     onero  age_of_asset (honap)  \
0          0      -0.029802     -0.180531  0.010955              0.603264   
1          0      -0.029802     -0.180531 -0.210588             -1.386171   
2          0      -0.029802     -0.180531 -0.210588             -0.365448   
3          0      -0.029802     -0.180531  0.728017              0.603264   
4          0      -0.029802     -0.180531 -0.210588              0.603264   
5          0      -0.029802     -0.180531 -0.210588             -0.365448   
6          0       0.276928     -0.180531  0.728017              0.603264   
7          0      -0.029802     -0.180531  0.010955              0.603264   
8          0      -0.029802     -0.180531 -0.210588             -0.365448   
9          0      -0.029802     -0.180531 -0.210588             -0.365448   

   sales_channel  Nace risk tier  
0       0.232891        0.585450  
1      -0.883030       -0.893508  
2       0.232891       -0.224232  
3       0.232891       -0.224232  
4       0.232891       -0.224232  
5      -0.883030        0.585450  
6       0.232891        0.585450  
7       0.232891        0.585450  
8       0.232891       -0.224232  
9       0.232891        0.585450

In [2]:

body = client_bc050f45180b4c1bb8886542b85a43fe.get_object(Bucket='szakdolgozat-donotdelete-pr-nxru0g4tgksnkv',Key='WOE_test.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

test_input = pd.read_csv(body, sep=';',decimal=',')
test_input.head()


DPD90_12m  customer_type  product_type     onero  age_of_asset (honap)  \
0          0      -0.029802     -0.180531  0.010955              0.603264   
1          0      -0.029802     -0.180531 -0.210588             -1.386171   
2          0      -0.029802     -0.180531  0.728017              0.603264   
3          0      -0.029802     -0.180531  0.728017              0.603264   
4          0      -0.029802     -0.180531 -0.210588              0.603264   

   sales_channel  Nace risk tier  
0       0.232891        0.585450  
1      -0.883030        0.585450  
2       0.232891        0.585450  
3       0.232891        0.585450  
4       0.232891       -0.893508

In [3]:
train_input.shape

(7339, 7)

In [4]:
test_input.shape

(3083, 7)

## Adatok előkészítése

In [5]:
import numpy as np

In [6]:
X_train = np.asarray(train_input[['onero', 'age_of_asset (honap)','sales_channel', 'Nace risk tier', 'customer_type', 'product_type']])
X_train[0:1]

array([[ 0.01095466,  0.6032641 ,  0.23289082,  0.58545026, -0.02980206,
        -0.18053093]])

In [7]:
X_test = np.asarray(test_input[['onero', 'age_of_asset (honap)','sales_channel', 'Nace risk tier', 'customer_type', 'product_type']])
X_test[0:1]

array([[ 0.01095466,  0.6032641 ,  0.23289082,  0.58545026, -0.02980206,
        -0.18053093]])

In [8]:
y_train = np.asarray(train_input['DPD90_12m'])
y_train [0:5]

array([0, 0, 0, 0, 0])

In [9]:
y_test = np.asarray(test_input['DPD90_12m'])
y_test [0:5]

array([0, 0, 0, 0, 0])

## Modellezés

In [15]:
import tensorflow as tf
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
    
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=50)


Train on 7339 samples
Epoch 1/50
7339/7339 [==============================] - 160s 22ms/sample - loss: 0.1877 - accuracy: 0.9557
Epoch 2/50
7339/7339 [==============================] - 155s 21ms/sample - loss: 0.1052 - accuracy: 0.9757
Epoch 3/50
7339/7339 [==============================] - 160s 22ms/sample - loss: 0.1044 - accuracy: 0.9757
Epoch 4/50
7339/7339 [==============================] - 166s 23ms/sample - loss: 0.1032 - accuracy: 0.9757
Epoch 5/50
7339/7339 [==============================] - 160s 22ms/sample - loss: 0.1033 - accuracy: 0.9757
Epoch 6/50
7339/7339 [==============================] - 156s 21ms/sample - loss: 0.1022 - accuracy: 0.9757
Epoch 7/50
7339/7339 [==============================] - 157s 21ms/sample - loss: 0.1030 - accuracy: 0.9757
Epoch 8/50
7339/7339 [==============================] - 163s 22ms/sample - loss: 0.1026 - accuracy: 0.9757
Epoch 9/50
7339/7339 [==============================] - 166s 23ms/sample - loss: 0.1023 - accuracy: 0.9757
Epoch 10/50
733

In [11]:
import tensorflow as tf
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1, activation='sigmoid')
    
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=35)

Train on 7339 samples
Epoch 1/35
7339/7339 [==============================] - 154s 21ms/sample - loss: 0.2476 - accuracy: 0.9509
Epoch 2/35
7339/7339 [==============================] - 155s 21ms/sample - loss: 0.1252 - accuracy: 0.9757
Epoch 3/35
7339/7339 [==============================] - 139s 19ms/sample - loss: 0.1218 - accuracy: 0.9757
Epoch 4/35
7339/7339 [==============================] - 138s 19ms/sample - loss: 0.1181 - accuracy: 0.9757
Epoch 5/35
7339/7339 [==============================] - 145s 20ms/sample - loss: 0.1178 - accuracy: 0.9757
Epoch 6/35
7339/7339 [==============================] - 152s 21ms/sample - loss: 0.1176 - accuracy: 0.9757
Epoch 7/35
7339/7339 [==============================] - 153s 21ms/sample - loss: 0.1160 - accuracy: 0.9757
Epoch 8/35
7339/7339 [==============================] - 146s 20ms/sample - loss: 0.1155 - accuracy: 0.9757
Epoch 9/35
7339/7339 [==============================] - 148s 20ms/sample - loss: 0.1149 - accuracy: 0.9757
Epoch 10/35
733

In [12]:
yhat_test = model.predict(X_test)
yhat_test

array([[0.00490914],
       [0.09100655],
       [0.00151733],
       ...,
       [0.07807841],
       [0.12457323],
       [0.0023592 ]], dtype=float32)

In [13]:
yhat_train = model.predict(X_train)
yhat_train

array([[0.00490914],
       [0.13664486],
       [0.04597035],
       ...,
       [0.00175901],
       [0.00166815],
       [0.05212386]], dtype=float32)

## Modell ereje

In [14]:
from sklearn.metrics import roc_auc_score
roc=roc_auc_score(y_train, yhat_train)
gini=2*roc-1
gini

0.5493426472041911

In [15]:
from sklearn.metrics import roc_auc_score
roc=roc_auc_score(y_test, yhat_test)
gini=2*roc-1
gini

0.5235114187209995