# Random Forest std


## Adatok betöltése

In [10]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_bc050f45180b4c1bb8886542b85a43fe = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='6akYbYHItNWmuiZPpgS8f0DnZNTVPSN3hYgF_EVLfHhd',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

body = client_bc050f45180b4c1bb8886542b85a43fe.get_object(Bucket='szakdolgozat-donotdelete-pr-nxru0g4tgksnkv',Key='Standard_train.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

train_input = pd.read_csv(body, sep=';',decimal=',')
train_input.head(10)


DPD90_12m  customer_type  product_type_zart  product_type_nyilt     onero  \
0          0              1                  1                   0  0.982666   
1          0              1                  1                   0 -0.474430   
2          0              1                  1                   0 -0.474430   
3          0              1                  1                   0  1.104222   
4          0              1                  1                   0 -0.271573   
5          0              1                  1                   0 -0.474430   
6          0              0                  1                   0  3.487986   
7          0              1                  1                   0  0.115986   
8          0              1                  1                   0 -1.263756   
9          0              1                  1                   0 -0.474430   

   age_of_asset (honap)  sales_channel_dealer  sales_channel_hitelpont  \
0             -0.540714                     1                        0   
1              2.285552                     0                        0   
2              1.225702                     1                        0   
3             -0.540714                     1                        0   
4             -0.540714                     1                        0   
5              0.872419                     0                        0   
6             -0.540714                     1                        0   
7             -0.540714                     1                        0   
8             -0.219548                     1                        0   
9              1.161469                     1                        0   

   sales_channel_hiteliroda  Nace_low  Nace_medium  Nace_high  
0                         0         1            0          0  
1                         1         0            0          1  
2                         0         0            1          0  
3                         0         0            1          0  
4                         0         0            1          0  
5                         1         1            0          0  
6                         0         1            0          0  
7                         0         1            0          0  
8                         0         0            1          0  
9                         0         1            0          0

In [11]:

body = client_bc050f45180b4c1bb8886542b85a43fe.get_object(Bucket='szakdolgozat-donotdelete-pr-nxru0g4tgksnkv',Key='Standard_test.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

test_input = pd.read_csv(body, sep=';',decimal=',')
test_input.head()


DPD90_12m  customer_type  product_type_zart  product_type_nyilt     onero  \
0          0              1                  1                   0  0.314896   
1          0              1                  1                   0 -0.474430   
2          0              1                  1                   0  1.618863   
3          0              1                  1                   0  1.104222   
4          0              1                  1                   0 -0.474430   

   age_of_asset (honap)  sales_channel_dealer  sales_channel_hitelpont  \
0             -0.540714                     1                        0   
1              2.670952                     0                        0   
2             -0.540714                     1                        0   
3             -0.540714                     1                        0   
4             -0.540714                     1                        0   

   sales_channel_hiteliroda  Nace_low  Nace_medium  Nace_high  
0                         0         1            0          0  
1                         1         1            0          0  
2                         0         1            0          0  
3                         0         1            0          0  
4                         0         0            0          1

In [12]:
train_input.shape

(7339, 12)

In [13]:
test_input.shape

(3083, 12)

## Adatok előkészítése

In [14]:
import numpy as np

In [15]:
X_train = np.asarray(train_input[['customer_type', 'product_type_zart', 'product_type_nyilt', 'sales_channel_dealer', 'sales_channel_hiteliroda', 'sales_channel_hitelpont', 'onero', 'age_of_asset (honap)', 'Nace_low', 'Nace_medium', 'Nace_high']])
X_train[0:1]

array([[ 1.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.98266592, -0.54071439,  1.        ,  0.        ,
         0.        ]])

In [16]:
X_test = np.asarray(test_input[['customer_type', 'product_type_zart', 'product_type_nyilt', 'sales_channel_dealer', 'sales_channel_hiteliroda', 'sales_channel_hitelpont', 'onero', 'age_of_asset (honap)', 'Nace_low', 'Nace_medium', 'Nace_high']])
X_test[0:1]

array([[ 1.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.31489619, -0.54071439,  1.        ,  0.        ,
         0.        ]])

In [17]:
y_train = np.asarray(train_input['DPD90_12m'])
y_train [0:5]

array([0, 0, 0, 0, 0])

In [18]:
y_test = np.asarray(test_input['DPD90_12m'])
y_test [0:5]

array([0, 0, 0, 0, 0])

## Modellezés

In [89]:
from sklearn.ensemble import RandomForestClassifier
LR = RandomForestClassifier(max_depth = 10, min_samples_split=0.01, n_estimators=1000).fit(X_train,y_train)
LR

RandomForestClassifier(max_depth=10, min_samples_split=0.01, n_estimators=1000)

In [90]:
yhat_test = LR.predict_proba(X_test)
yhat_test

array([[9.97263366e-01, 2.73663404e-03],
       [9.17551589e-01, 8.24484112e-02],
       [9.99605708e-01, 3.94292392e-04],
       ...,
       [8.92882326e-01, 1.07117674e-01],
       [7.93784517e-01, 2.06215483e-01],
       [9.99332177e-01, 6.67823025e-04]])

In [91]:
yhat_train = LR.predict_proba(X_train)
yhat_train

array([[9.93122121e-01, 6.87787857e-03],
       [8.84476914e-01, 1.15523086e-01],
       [9.74970205e-01, 2.50297948e-02],
       ...,
       [9.99218852e-01, 7.81148079e-04],
       [9.99039821e-01, 9.60179444e-04],
       [8.81638470e-01, 1.18361530e-01]])

In [92]:
tech, y_predicted_train = zip(*yhat_train)
y_predicted_train[0:5]

(0.006877878566311099,
 0.11552308633395597,
 0.02502979479639071,
 0.025392907920881794,
 0.02247093691720541)

In [93]:
tech, y_predicted_test = zip(*yhat_test)
y_predicted_test[0:5]

(0.0027366340370791873,
 0.08244841118708703,
 0.0003942923917895935,
 0.0009493232388403293,
 0.03791272327802737)

## Modell ereje

In [94]:
from sklearn.metrics import roc_auc_score
roc=roc_auc_score(y_train, y_predicted_train)
gini=2*roc-1
gini

0.8068211237837914

In [95]:
from sklearn.metrics import roc_auc_score
roc=roc_auc_score(y_test, y_predicted_test)
gini=2*roc-1
gini

0.4542991938201517