# SVM std


## Adatok betöltése

In [1]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_bc050f45180b4c1bb8886542b85a43fe = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='6akYbYHItNWmuiZPpgS8f0DnZNTVPSN3hYgF_EVLfHhd',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

body = client_bc050f45180b4c1bb8886542b85a43fe.get_object(Bucket='szakdolgozat-donotdelete-pr-nxru0g4tgksnkv',Key='Standard_train.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

train_input = pd.read_csv(body, sep=';',decimal=',')
train_input.head(10)


DPD90_12m  customer_type  product_type_zart  product_type_nyilt     onero  \
0          0              1                  1                   0  0.982666   
1          0              1                  1                   0 -0.474430   
2          0              1                  1                   0 -0.474430   
3          0              1                  1                   0  1.104222   
4          0              1                  1                   0 -0.271573   
5          0              1                  1                   0 -0.474430   
6          0              0                  1                   0  3.487986   
7          0              1                  1                   0  0.115986   
8          0              1                  1                   0 -1.263756   
9          0              1                  1                   0 -0.474430   

   age_of_asset (honap)  sales_channel_dealer  sales_channel_hitelpont  \
0             -0.540714                     1                        0   
1              2.285552                     0                        0   
2              1.225702                     1                        0   
3             -0.540714                     1                        0   
4             -0.540714                     1                        0   
5              0.872419                     0                        0   
6             -0.540714                     1                        0   
7             -0.540714                     1                        0   
8             -0.219548                     1                        0   
9              1.161469                     1                        0   

   sales_channel_hiteliroda  Nace_low  Nace_medium  Nace_high  
0                         0         1            0          0  
1                         1         0            0          1  
2                         0         0            1          0  
3                         0         0            1          0  
4                         0         0            1          0  
5                         1         1            0          0  
6                         0         1            0          0  
7                         0         1            0          0  
8                         0         0            1          0  
9                         0         1            0          0

In [2]:

body = client_bc050f45180b4c1bb8886542b85a43fe.get_object(Bucket='szakdolgozat-donotdelete-pr-nxru0g4tgksnkv',Key='Standard_test.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

test_input = pd.read_csv(body, sep=';',decimal=',')
test_input.head()


DPD90_12m  customer_type  product_type_zart  product_type_nyilt     onero  \
0          0              1                  1                   0  0.314896   
1          0              1                  1                   0 -0.474430   
2          0              1                  1                   0  1.618863   
3          0              1                  1                   0  1.104222   
4          0              1                  1                   0 -0.474430   

   age_of_asset (honap)  sales_channel_dealer  sales_channel_hitelpont  \
0             -0.540714                     1                        0   
1              2.670952                     0                        0   
2             -0.540714                     1                        0   
3             -0.540714                     1                        0   
4             -0.540714                     1                        0   

   sales_channel_hiteliroda  Nace_low  Nace_medium  Nace_high  
0                         0         1            0          0  
1                         1         1            0          0  
2                         0         1            0          0  
3                         0         1            0          0  
4                         0         0            0          1

In [3]:
train_input.shape

(7339, 12)

In [4]:
test_input.shape

(3083, 12)

## Adatok előkészítése

In [5]:
import numpy as np

In [6]:
X_train = np.asarray(train_input[['customer_type', 'product_type_zart', 'product_type_nyilt', 'sales_channel_dealer', 'sales_channel_hiteliroda', 'sales_channel_hitelpont', 'onero', 'age_of_asset (honap)', 'Nace_low', 'Nace_medium', 'Nace_high']])
X_train[0:1]

array([[ 1.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.98266592, -0.54071439,  1.        ,  0.        ,
         0.        ]])

In [7]:
X_test = np.asarray(test_input[['customer_type', 'product_type_zart', 'product_type_nyilt', 'sales_channel_dealer', 'sales_channel_hiteliroda', 'sales_channel_hitelpont', 'onero', 'age_of_asset (honap)', 'Nace_low', 'Nace_medium', 'Nace_high']])
X_test[0:1]

array([[ 1.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.31489619, -0.54071439,  1.        ,  0.        ,
         0.        ]])

In [8]:
y_train = np.asarray(train_input['DPD90_12m'])
y_train [0:5]

array([0, 0, 0, 0, 0])

In [9]:
y_test = np.asarray(test_input['DPD90_12m'])
y_test [0:5]

array([0, 0, 0, 0, 0])

## Modellezés

In [31]:
from sklearn.svm import SVC
LR = SVC(probability=True, kernel='sigmoid').fit(X_train,y_train)
LR

SVC(kernel='sigmoid', probability=True)

In [32]:
yhat_test = LR.predict_proba(X_test)
yhat_test

array([[0.97505381, 0.02494619],
       [0.97501675, 0.02498325],
       [0.9753357 , 0.0246643 ],
       ...,
       [0.97454462, 0.02545538],
       [0.97523899, 0.02476101],
       [0.97513853, 0.02486147]])

In [33]:
yhat_train = LR.predict_proba(X_train)
yhat_train

array([[0.97517541, 0.02482459],
       [0.9751907 , 0.0248093 ],
       [0.9751837 , 0.0248163 ],
       ...,
       [0.97502426, 0.02497574],
       [0.97509786, 0.02490214],
       [0.97525877, 0.02474123]])

In [34]:
tech, y_predicted_train = zip(*yhat_train)
y_predicted_train[0:5]

(0.02482458661409059,
 0.024809304104093724,
 0.024816302197119174,
 0.024968258786502943,
 0.024998261601902626)

In [35]:
tech, y_predicted_test = zip(*yhat_test)
y_predicted_test[0:5]

(0.024946186663494886,
 0.024983248042286257,
 0.024664298040805818,
 0.02479551156789733,
 0.02486220979256594)

## Modell ereje

In [36]:
from sklearn.metrics import roc_auc_score
roc=roc_auc_score(y_train, y_predicted_train)
gini=2*roc-1
gini

-0.02369106066097737

In [37]:
from sklearn.metrics import roc_auc_score
roc=roc_auc_score(y_test, y_predicted_test)
gini=2*roc-1
gini

0.01159585590723311